---

# Calculated variables during playbook run

# Software source directory
splunk_software: "{% if splunk_software_dir | regex_search('^/') %}{{ splunk_software_dir }}{% else %}{{ playbook_dir }}/../{{ splunk_software_dir }}{% endif %}"

# Baseconfig apps directory
splunk_baseconfig: "{% if splunk_baseconfig_dir | regex_search('^/') %}{{ plunk_baseconfig_dir }}{% else %}{{ playbook_dir }}/../{{ splunk_baseconfig_dir }}{% endif %}"
splunk_app_prefix: "{{ splunk_env_name|default('splunk') }}"

# Splunk Roles
splunk_roles: >-
          {%- set res = [] -%}
          {%- for role_name in groups|map('regex_search','role_.*')|select('string')|list -%}
            {%- if inventory_hostname in groups[role_name] -%}
              {%- set ignored = res.extend([role_name|replace("role_","")]) -%}
            {%- endif -%}
          {%- endfor -%}
          {{ res|join(', ') }}

# Output Definitions
splunk_outputs_idxc_list: "{{ splunk_outputs_list['idxcluster']|default({}) }}"
splunk_outputs_idx_list: "{{ splunk_outputs_list['indexer']|default([]) }}"
splunk_outputs_name_list: >-
          {%- set res = [] -%}
          {%- for host in groups['all']|intersect(groups['splunk_env_'+splunk_env_name]) -%}
            {%- set ignored = res.extend([hostvars[host]['splunk_outputs']]) -%}
          {%- endfor -%}
          {{ res|unique }}

# Search Peer Definitions
splunk_search_peer_idxc_list: "{{ splunk_search_peer_list['idxcluster']|default([]) }}"
splunk_search_peer_idx_list: "{{ splunk_search_peer_list['indexer']|default([]) }}"
splunk_search_peer_name_list: >-
          {%- set res = [] -%}
          {%- for host in groups['all']|intersect(groups['splunk_env_'+splunk_env_name]) -%}
            {%- set ignored = res.extend([hostvars[host]['splunk_search_peers']]) -%}
          {%- endfor -%}
          {{ res|unique }}

# Indexer Cluster
splunk_idxc_name_list: "{{ groups|map('regex_search','idxcluster_.*')|select('string')|list }}"
splunk_idxc_label: "{{ idxc_name }}"
splunk_idxc_pass: "{{ idxc_password }}"
splunk_idxc_replication_port: "{{ idxc_replication_port }}"
splunk_idxc_rf: "{{ idxc_rf }}"
splunk_idxc_sf: "{{ idxc_sf }}"
splunk_idxc_cm: "{% for cm in groups.role_cluster_master|default([]) %}{% if cm in groups['idxcluster_'+idxc_name] %}{{ cm }}{% endif %}{% endfor %}"
splunk_idxc_cm_list: >-
           {% set res = [] -%}
           {%- for idxc in splunk_idxc_name_list -%}
             {% set ignored = res.extend(groups[idxc]|list) -%}
           {%- endfor -%}
           {{ res|unique|intersect(groups.role_cluster_master|default([]))|intersect(groups['splunk_env_'+splunk_env_name]) }}

# Multisite Indexer Cluster
splunk_idxc_available_sites: "{{ idxc_available_sites|default([])|join(',') }}"
splunk_idxc_site_rf: "{{ idxc_site_rf }}"
splunk_idxc_site_sf: "{{ idxc_site_sf }}"

# Single Indexer
splunk_idxc_all_host_list: >-
          {%- set res = [] -%}
          {%- for group in splunk_idxc_name_list -%}
            {%- set ignored = res.extend(
              groups[group]
              ) -%}
          {%- endfor -%}
          {{ res|unique|intersect(groups.role_indexer|default([])) }}
splunk_indexer_list: "{{ groups.role_indexer|default([])|difference(splunk_idxc_all_host_list|default([]))|intersect(groups['splunk_env_'+splunk_env_name]) }}"

# Heavy Forwarder
splunk_heavy_forwarder_list: "{{ groups.role_heavy_forwarder|default([])|intersect(groups['splunk_env_'+splunk_env_name]) }}"

# Single Search Head
splunk_shc_name_list: "{{ groups|map('regex_search','shcluster_.*')|select('string')|list }}"
splunk_shc_all_host_list: >-
          {%- set res = [] -%}
          {%- for group in splunk_shc_name_list -%}
            {%- set ignored = res.extend(
              groups[group]|list
              ) -%}
          {%- endfor -%}
          {{ res|unique|intersect(groups.role_search_head|default([]))|intersect(groups['splunk_env_'+splunk_env_name]) }}
splunk_search_head_list: "{{ groups.role_search_head|default([])|union(groups.role_monitoring_console|default([]))|difference(splunk_shc_all_host_list|default([]))|difference(groups.role_cluster_master|default([]))|intersect(groups['splunk_env_'+splunk_env_name]) }}"

# Search Head Cluster
splunk_shc_label: "{{ shc_name }}"
splunk_shc_site: "{%- if shc_site is defined -%}{{ shc_site }}{%- else -%}site0{%- endif -%}"
splunk_shc_pass: "{{ shc_password }}"
splunk_shc_replication_port: "{{ shc_replication_port }}"
splunk_shc_host_list: "{{ groups['shcluster_'+shc_name]|intersect(groups.role_search_head|default([])) }}"
splunk_shc_deployer: "{% for dp in groups.role_deployer|default([]) %}{% if dp in groups['shcluster_'+shc_name] %}{{ dp }}{% endif %}{% endfor %}"
splunk_shc_dp_list: >-
           {% set res = [] -%}
           {%- for shc in splunk_shc_name_list -%}
            {% set ignored = res.extend(groups[shc]|list) -%}
           {%- endfor -%}
           {{ res|unique|intersect(groups.role_deployer|default([]))|intersect(groups['splunk_env_'+splunk_env_name]) }}


# Deployment Server
splunk_deployment_server: "{{groups.role_deployment_server|default([])|intersect(groups['splunk_env_'+splunk_env_name])|union(vagrant_splunk_deployment_server|default([]))|default([])}}"
splunk_idx_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in splunk_indexer_list|difference([splunk_deployment_server|first]) -%}
            {% set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}
splunk_idx_hf_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in splunk_indexer_list|union(splunk_heavy_forwarder_list)|difference([splunk_deployment_server|first]) -%}
            {% set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}
splunk_sh_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in splunk_search_head_list|difference([splunk_deployment_server|first]) -%}
            {%- set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}
splunk_sh_hf_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in splunk_search_head_list|union(splunk_heavy_forwarder_list)|difference([splunk_deployment_server|first]) -%}
            {%- set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}
splunk_idx_hf_sh_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in splunk_indexer_list|union(splunk_heavy_forwarder_list)|union(splunk_search_head_list)|difference([splunk_deployment_server|first]) -%}
            {% set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}
splunk_hf_sh_lm_cm_ds_dp_mc_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in splunk_heavy_forwarder_list|union(splunk_search_head_list)|union(splunk_license_master)|union(splunk_idxc_cm_list)|union(splunk_deployment_server)|union(splunk_shc_dp_list)|union(splunk_monitoring_console)|difference([splunk_deployment_server|first]) -%}
            {% set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}
splunk_license_dsclients: >-
          {%- set res = [] -%}
          {%- for ds_client in groups.all|intersect(groups['splunk_env_'+splunk_env_name])|unique|difference(splunk_idxc_all_host_list)|difference(splunk_shc_all_host_list|default([]))|difference(groups.role_license_master|default([]))|difference(groups.role_universal_forwarder|default([]))|difference([splunk_deployment_server|first]) -%}
            {%- set ignored = res.extend([{'server': ds_client, 'num':loop.index0}]) -%}
          {%- endfor -%}
          {{ res|unique }}

# Splunk Monitoring Console
splunk_monitoring_console: "{{groups.role_monitoring_console|default([])|intersect(groups['splunk_env_'+splunk_env_name])|union(vagrant_splunk_monitoring_console|default([]))|default([])}}"
splunk_dservers: "{{ groups.all|intersect(groups['splunk_env_'+splunk_env_name])|unique|difference(splunk_idxc_all_host_list)|difference(groups.role_monitoring_console|default([]))|difference(groups.role_universal_forwarder|default([])) }}"

# License Server
splunk_license_master: "{{groups.role_license_master|default([])|intersect(groups['splunk_env_'+splunk_env_name])|union(vagrant_splunk_license_master|default([]))|default([])}}"

