---
splunk_env_name: splk
splunk_version: latest
splunk_admin_password: splunklab
splunk_outputs: all
splunk_search_peers: all
splunk_secret_share:
  splunk: false
  splunkforwarder: false
  equal: false
splunk_volume_defaults:
  homePath: primary
  coldPath: primary
splunk_ssl:
  web:
    enable: false
    own_certs: false
    config:
      enableSplunkWebSSL: true
      privKeyPath: etc/auth/{{splunk_env_name}}/privkey.web.key
      serverCert: etc/auth/{{splunk_env_name}}/cacert.web.pem
  inputs:
    enable: false
    own_certs: false
    config:
      rootCA: "$SPLUNK_HOME/etc/auth/cacert.pem"
      serverCert: "$SPLUNK_HOME/etc/auth/server.pem"
  outputs:
    enable: false
    own_certs: false
    config:
      sslRootCAPath: "$SPLUNK_HOME/etc/auth/cacert.pem"
      sslCertPath: "$SPLUNK_HOME/etc/auth/client.pem"
      sslPassword: password
vagrant_splunk_monitoring_console:
- cm
vagrant_splunk_deployment_server:
- cm
