---
# splunk_config.yml

# General settings
general:
  start_ip: 172.16.1.100

# Ansible configs
ansible:
  # Verbose output
  verbose: "v"
  # Skip ansible tags, ex. skip whole splunk install/config
  skip_tags:
#    - common
#    - splunk

# Virtualbox settings
virtualbox:
  box: "centos/7"
#  box: "ubuntu/xenial64"
  memory: 512
  cpus: 1
  # Install vbox guest additions
  install_vbox_additions: false # true/false
  # You need to install vagrant plugin vagrant-vbguest to mount folders
  synced_folder:
#    -  source: "../../Documents/Splunk/Software"
#       target: "/Splunk_Software"

# Operating System definitions
os:
  # The timezone defaults to the vagrant host timezone, but you can set another one here
  time_zone: "America/New York"
  # Install additional packages
  packages:
    - unzip
    - epel-release
#    - lsof

splunk_defaults:
#  splunk_env_name: splunk1
#  splunk_version: '7.0.0'
#  splunk_admin_password: 'splunklab1'
  # Give a path to a license file. Must be located in splunk_software_dir
#  splunk_license_file: Splunk_Enterprise1.lic
  # Enable https for Splunk web
#  splunk_ssl:
#    web:
#      enable: true
#      own_certs: true
  # Define some indexes to be created on the indexers
#  splunk_indexes:
#    - test1
#    - test2

# Share the same splunk.secret file for all installations.
  splunk_secret_share:
    # for Splunk Enterprise
    splunk: true
    # for Splunk Universal Forwarders
    splunkforwarder: true
    # use the same for both install types
    equal: true

splunk_basics:
    # Location of the extracted baseconfig apps
    splunk_baseconfig_dir: ../Software
    # This is where the splunk install archives are searched for
    splunk_software_dir: ../Software

# Splunk general settings
splunk_environments:
  - splunk_env_name: splunk1
    splunk_version: '7.0.1'
    splunk_admin_password: 'splunklab'
    # Give a path to a license file. Must be located in splunk_software_dir
    splunk_license_file: Splunk_Enterprise.lic
    # Define some indexes to be created on the indexers
    splunk_indexes:
      - test1
      - test2
      - os

# Indexer Cluster settings
splunk_idxclusters:
  - idxc_name: idxc1
    idxc_password: splunkidxc
    idxc_replication_port: 9887
    idxc_site_rf: 'origin:2, total:2'
    idxc_site_sf: 'origin:2, total:2'

# Search Head Cluster settings
splunk_shclusters:
  - shc_name: shc1
    shc_site: site0
    shc_password: splunkshc
    shc_replication_port: 9887

# Splunk hosts with its settings
splunk_hosts:
  # Cluster Master
  - name: cm
# You can set ansible settings here as well
#    ansible:
#      verbose: "v"
#      skip_tags:
#        - splunk
# You can set host specific vbox resources here as well
    virtualbox:
      cpus: 2
      memory: 1024
# You can set an ip addr here, which overrides the dynamic one
#    ip_addr: 192.168.2.210
# You can also set os specific configurations here
    os:
      time_zone: "America/Los_Angeles"
      # Install additional packages
      packages:
        - unzip
        - lsof
    roles:
      - cluster_master
      - license_master
    # Name the indexer cluster to be master of
    idxcluster: idxc1
    site: site0
    # Specify different version fot this host
    splunk_version: '6.5.3'

  # Cluster Indexer
  - name: idx1
    roles:
      - indexer
    # Name the indexer cluster to be a member of
    idxcluster: idxc1
    site: site1

  # Cluster Indexer
  - name: idx2
    roles:
      - indexer
    idxcluster: idxc1
    site: site1

  # Cluster Indexer
  - name: idx3
    roles:
      - indexer
    idxcluster: idxc1
    site: site2

  # Cluster Indexer
  - name: idx4
    roles:
      - indexer
    idxcluster: idxc1
    site: site2

  # Deployment Server
  - name: ds
    roles:
      - deployment_server
      - deployer
    # Name the search head cluster deploy packages to
    shcluster: shc1

  # Single Indexer
  - name: idx5
    roles:
      - indexer

  # Cluster Search Head
  - name: sh1
    roles:
      - search_head
    # Name the search head cluster to be a member of
    shcluster: shc1

  # Cluster Search Head
  - name: sh2
    roles:
      - search_head
    shcluster: shc1

  # SCluster earch Head
  - name: sh3
    roles:
      - search_head
    shcluster: shc1

  # Single Search Head
  - name: smc
    roles:
      - monitoring_console

  # Heavy Forwarder
  - name: hf1
    roles:
      - heavy_forwarder

  # Universal Forwarder
  - name: uf1
    roles:
      - universal_forwarder
